name: Build and Push Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: docker/setup-qemu-action@v2
            - uses: docker/setup-buildx-action@v2
            - uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: kristn1/postal2-server:latest
                  file: ./Dockerfile
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - uses: peter-evans/dockerhub-description@v4
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  repository: kristn1/postal2-server
